export type Technology = {
  name: string;
  icon: string;
};

export const techStack: Technology[] = [
  { name: "React", icon: "/tech-stack/react.svg" },
  { name: "Next.js", icon: "/tech-stack/nextjs.svg" },
  { name: "Nest.js", icon: "/tech-stack/nestjs.svg" },
  { name: "TypeScript", icon: "/tech-stack/typescript.svg" },
  { name: "JavaScript", icon: "/tech-stack/js.svg" },
  { name: "Python", icon: "/tech-stack/python.svg" },
  { name: "Django", icon: "/tech-stack/django.svg" },
  { name: "Node.js", icon: "/tech-stack/nodejs.svg" },
  { name: "Express.js", icon: "/tech-stack/expressjs.svg" },
  { name: "MongoDB", icon: "/tech-stack/mongodb.png" },
  { name: "Mongoose", icon: "/tech-stack/mongoose.svg" },
  { name: "MySQL", icon: "/tech-stack/mysql.svg" },
  { name: "Prisma", icon: "/tech-stack/prisma.svg" },
  { name: "Supabase", icon: "/tech-stack/supabase.svg" },
  { name: "GraphQL", icon: "/tech-stack/graphql.svg" },
  { name: "HTML5", icon: "/tech-stack/html5.png" },
  { name: "CSS3", icon: "/tech-stack/css3.svg" },
  { name: "Sass", icon: "/tech-stack/sass.svg" },
  { name: "Material UI", icon: "/tech-stack/materialui.svg" },
  { name: "Redux", icon: "/tech-stack/redux.svg" },
  { name: "React Router", icon: "/tech-stack/reactrouter.svg" },
  { name: "Vue.js", icon: "/tech-stack/vuejs.svg" },
  { name: "Vite", icon: "/tech-stack/vitejs.svg" },
  { name: "Webpack", icon: "/tech-stack/webpack.svg" },
  { name: "Docker", icon: "/tech-stack/docker.svg" },
  { name: "AWS", icon: "/tech-stack/aws.svg" },
  { name: "Vercel", icon: "/tech-stack/vercel.svg" },
  { name: "Heroku", icon: "/tech-stack/heroku.svg" },
  { name: "Railway", icon: "/tech-stack/railway.svg" },
  { name: "Git", icon: "/tech-stack/git.svg" },
  { name: "GitHub", icon: "/tech-stack/github.svg" },
  { name: "GitLab", icon: "/tech-stack/gitlab.svg" },
  { name: "NPM", icon: "/tech-stack/npm2.svg" },
  { name: "Jest", icon: "/tech-stack/jest.svg" },
  { name: "Postman", icon: "/tech-stack/postman.svg" },
  { name: "Jira", icon: "/tech-stack/jira.svg" },
  { name: "Stripe", icon: "/tech-stack/stripe.svg" },
  { name: "VS Code", icon: "/tech-stack/vscode.svg" },
];
